version: "3.8"

services:
  quasar-admin:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    command: sh -c "npm install && npx quasar dev -p 9000"
    environment:
      - NODE_ENV=development
