services:
  quasar-app:
    build: .
    container_name: vue-quasar-frontend
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.quasar
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped